### ISSUE TITLE
cant compile source

### ISSUE THREAD

**Issue by oakieville** [bucanero/pkgi-ps3#24]
installed the dependencies and try to compile it i get alot of errors isk what i have wrong errors like input redined and config redifined

**Comment by bucanero** [comment]
this issue is most probably related to the fact that you might be using an old GCC cross-compiler on your toolchain. The code syntax is not handled properly by the old compiler.  
My ps3 toolchain is using gcc 7.2.0 , but for example the pre-built "PS3SDKv2" has gcc 4.x.x . 

The gcc problem was originally reported by @blckbearx . Check https://github.com/bucanero/pkgi-ps3/pull/1 since he submitted a fix to compile the code with the old toolchain.

**Comment by bucanero** [comment]
This issue has been solved in #1  (https://github.com/bucanero/pkgi-ps3/commit/40c58a26a70e0d80a78b5ed22eef9567239c3873). Check out the master branch.
