### ISSUE TITLE
install does not actually install

### ISSUE THREAD

**Issue by mohasi** [bucanero/pkgi-ps3#43]
Pressing X to install a package does not actually install it, it just downloads it. I suggest renaming this to download or actually installing the package.

In addition, please if you could change the UI so that the `O` button closes the side menu instead of resetting it, I always forget to press `Triangle`. Normally `O` represents back in everything.

**Comment by bucanero** [comment]
> Pressing X to install a package does not actually install it, it just downloads it. I suggest renaming this to download or actually installing the package.

I guess `Download` would fit better. I never paid too much attention, mostly because this is a port of pkgi-vita, and all the screens and messages where inherited.

> In addition, please if you could change the UI so that the `O` button closes the side menu instead of resetting it, I always forget to press `Triangle`. Normally `O` represents back in everything.

Again, this behavior was inherited from the Vita. Even now, pkgj-vita uses `triangle` to open/save the settings. Not sure why they made that choice.
