### ISSUE TITLE
Startup Issue

### ISSUE THREAD

**Issue by jokesonyou123** [bucanero/pkgi-ps3#44]
When loading up PKGI, the error message for config/pkgi.txt shows up and none of the buttons work and nothing opens up.

**Comment by mohasi** [comment]
@jokesonyou123 Did you follow the instructions? You need to FTP (or use some file manager) onto your PS3 then go and add the `pkgi.txt` file in the correct place.

**Comment by bucanero** [comment]
The app doesn't include any kind of link or file. You need to provide your own files. Here's the information: https://pkgi.psdev.tk/#setup-instructions

**Comment by jokesonyou123** [comment]
I originally put the pkgi.txt file in the wrong folder, now it's placed in the USRDIR folder but it still shows the same screen when I start it up.

Should I transfer include the dbformat.txt file in the USRDIR folder as well?

**Comment by mohasi** [comment]
> I originally put the pkgi.txt file in the wrong folder, now it's placed in the USRDIR folder but it still shows the same screen when I start it up.
> 
> Should I transfer include the dbformat.txt file in the USRDIR folder as well?

So it does that, even if the file is in there, its because it wants everything to be correct. I had a config.txt, pkgi.txt and dbformat.txt and it would still complain until I had everything correct. In the end it was because the urls inside the config were using HTTPS instead of HTTP, but the error message was misleading saying the file was not there at all.
